name: Build and Deployement

on: push

permissions: 
    contents: write

jobs:
    build-project:
        runs-on: ubuntu-latest
        steps:
                - name: Checkout
                  uses: actions/checkout@v4
                  with:
                    repository: 'kf1375/EtherCan_Software_RTOS'
                
                - name: Build
                  uses: xanderhendriks/action-build-stm32cubeide@v10.0
                  with:
                    project-path: './'
                    project-target: '.project'

                - name: Copy out .elf file
                  run: docker container ls
        
